---
- hosts: vm
  become: True
  tasks:
  - name: Install python pip
    yum:
      name: python-pip
      state: present
  - name: Install docker-py python module
    pip:
      name: docker-py
      state: present
  - name: Start the container
    docker_container:
      name: simple-java-web
      image: "leminhthu/simple-java-web:{{DOCKER_TAG}}"
      state: started
      published_ports:
      - 0.0.0.0.8080:9999
